---
- name: checking the database connection
  hosts: ops
  gather_facts: no
  vars:
    ansible_ssh_user: admin
  tasks:
    - name: checking if I can execute `ovsdb-client dump` on the switch
      command: ovsdb-client dump
      become: yes
